"""create new tables

Revision ID: 6eb923a607aa
Revises: 18e3b17c607d
Create Date: 2022-11-23 10:40:53.217744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb923a607aa'
down_revision = '18e3b17c607d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('shipping_instructions', sa.String(length=100), nullable=True))
    op.drop_column('purchases', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('total_price', sa.FLOAT(), nullable=True))
    op.drop_column('purchases', 'shipping_instructions')
    # ### end Alembic commands ###
